### ISSUE TITLE
How to Install Apache Cassandra on Ubuntu 17.04 and CentOS 7 Proposed Changes

### ISSUE THREAD

**Issue by rytvish** [linode/docs#1518]
Link: https://linode.com/docs/databases/cassandra/deploy-scalable-cassandra/
## Issue
OS: Ubuntu 16.04
RAM: 1GB
Storage: 8GB
Cassandra service is running but ports are not coming up. Kindly help

cat /etc/cassandra/cassandra-env.sh | grep rmi.server.hostnam
JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=127.0.0.1"

INFO  [main] 2018-02-17 07:36:49,826 ViewManager.java:137 - Not submitting build tasks for views in keyspace system as storage service is not initialized
ERROR [main] 2018-02-17 07:36:50,107 CassandraDaemon.java:747 - Exception encountered during startup
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFilter;)Ljava/rmi/Remote;
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150) ~[na:1.8.0_161]
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135) ~[na:1.8.0_161]
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405) ~[na:1.8.0_161]
        at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:106) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:145) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:219) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730) [apache-cassandra-3.9.jar:3.9]

**Comment by rytvish** [comment]
After a lot of digging, i found out that there is some issue with the recent oracle 161 update, hence downgraded to 152 and it started working.....URL for your reference. 
https://issues.apache.org/jira/browse/CASSANDRA-14173
